version: "3.1"
services:
  # postgres service, you can comment it if you aleardy have a postgress instance to connect
  pgsql:
    container_name: pgsql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "root_password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "sparow"
    ports:
      - 5432:5432
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
  # main service of sparow
  core:
    container_name: sparow_core
    build: ./
    restart: always
    environment:
      APP_NAME: "salimon"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - 5000:80
    depends_on:
      - pgsql

networks:
  default:
    external:
      name: salimon
