version: "3.1"
services:
  # postgres service, you can comment it if you aleardy have a postgress instance to connect
  pgsql:
    container_name: pgsql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "root_password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "sparow"
    ports:
      - 5432:5432
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
