apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: pgsql
  name: pgsql
  namespace: salimon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: pgsql
        name: pgsql
    spec:
      containers:
        - image: postgres:latest
          env:
            - name: "POSTGRES_PASSWORD"
              value: "root_password"
            - name: "POSTGRES_USER"
              value: "root"
            - name: "POSTGRES_DB"
              value: "sparow"
          imagePullPolicy: IfNotPresent
          name: ghost
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
            requests:
              cpu: "0.1"
              ephemeral-storage: 1G
              memory: 200M
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql
