name: deploy image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker
        uses: docker/login-action@v1.8.0
        with:
          username: salimondev
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          tags: salimondev/sparow-core:latest
          push: true
      - name: Login to Okteto
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Activate Namespace
        uses: okteto/namespace@v4.1
        with:
          namespace: mr-exception
      - name: Deploy Stack
        uses: okteto/deploy-stack@v4.1
        with:
          build: true
          namespace: mr-exception
        env:
          APP_NAME: sparow-core
          DB_USERNAME: ${{ secrets.PGSQL_USERNAME }}
          DB_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
